// isr_amd64.s - interrupt stubs
#include "textflag.h"

// Macro to define an interrupt stub.
// For vectors that push an error code, we must not push an extra dummy.
// We'll define two types: with and without error code.
// For simplicity, we'll push the vector number (which is known at build time) and a dummy error code if needed.
// We'll use a common pattern: we store the vector number in a global table? Or we generate individual functions.

// We'll generate a function for each vector that calls the Go handler with vector number and context.

// The common handler will save all registers, call the Go function, then restore and iret.

// Define a macro to generate a stub.
// It pushes the vector number, then jumps to common_handler.
#define ISR_STUB(vector, has_error) \
TEXT ·isr_##vector(SB), NOSPLIT, $0; \
    PUSHQ $0; /* dummy error code */ \
    PUSHQ $vector; \
    JMP common_isr_handler;

// For vectors that have error codes, we skip the dummy push.
#define ISR_STUB_ERR(vector) \
TEXT ·isr_##vector(SB), NOSPLIT, $0; \
    PUSHQ $vector; \
    JMP common_isr_handler;

// We'll define stubs for all 256 vectors. To save space, we'll generate them using a script, but we'll manually implement a few for demonstration.
// We'll implement a generic approach: a single stub that reads the vector from the interrupt frame? But that's not possible because the vector is not passed automatically.
// So we must generate a function per vector.

// We'll use a table of function pointers in Go, and we'll populate them via assembly.
// But simpler: we'll create a single assembly function that takes vector as argument? Not possible because the CPU doesn't push it.
// So we'll generate 256 stubs using a macro.

// We'll place them in a separate file generated by a script or use repeated macro calls.
// For brevity, we'll define only the first 32 (exceptions + IRQs) and then a generic stub for the rest that prints a message.

// For production, we can generate with a script.
// We'll produce here a representative set.

// We'll define a macro for the common handler:
TEXT common_isr_handler(SB), NOSPLIT, $0
    // Save all general-purpose registers
    PUSHQ RAX
    PUSHQ RBX
    PUSHQ RCX
    PUSHQ RDX
    PUSHQ RSI
    PUSHQ RDI
    PUSHQ RBP
    PUSHQ R8
    PUSHQ R9
    PUSHQ R10
    PUSHQ R11
    PUSHQ R12
    PUSHQ R13
    PUSHQ R14
    PUSHQ R15

    // The stack now has: vector, error, saved RIP, CS, RFLAGS, RSP, SS (if ring 0)
    // We need to pass a pointer to this context to the Go handler.
    // We'll pass the vector (which is at the top of stack after pushes) and the pointer to the saved context.
    // We'll use a Go function: void handleInterrupt(uint8 vector, void* context)
    // The context can be the stack pointer after pushing all registers? But we need to include the pushed registers plus the original frame.
    // We'll just pass the current RSP, and the Go code will interpret it.

    MOVQ RSP, RDI       // first arg: pointer to saved registers
    MOVQ 16(RSP), RSI   // vector is at (RSP + 16?) Actually after pushes, the top is R15, then R14, ..., RAX, then vector, error, then original frame.
    // Let's compute: after pushing 15 registers (R15..RAX), the stack pointer points to RAX. Above that is vector (pushed earlier) and error (dummy).
    // So vector is at RSP + 15*8? Actually we pushed 15 regs, so RSP is at RAX. The vector is at RSP + 15*8. But we need to be careful.
    // We'll do: MOVQ 15*8(RSP), RSI   but that's not reliable because we didn't push RBP? We pushed RBP too.
    // Let's count: we pushed RAX, RBX, RCX, RDX, RSI, RDI, RBP, R8, R9, R10, R11, R12, R13, R14, R15 -> that's 15 registers.
    // So vector is at RSP + 15*8? Actually the first push is R15, then R14... last is RAX. So after all pushes, the top is RAX, then next is original RSP? Wait:
    // Before pushes, the stack had: [vector][error][rip][cs][rflags][rsp][ss] (if ring 0). After push RAX, the stack is [rax][vector][error][rip]... Actually we push RAX, so it goes on top: [rax][vector][error][rip]...
    // So after pushing all 15 regs, the stack is [r15][r14]...[rax][vector][error][rip]...
    // The top is R15. So vector is at RSP + 15*8? Let's compute: RSP points to R15, RSP+8 points to R14, ..., RSP+14*8 points to RAX, RSP+15*8 points to vector.
    // So MOVQ 15*8(RSP), RSI  gets the vector.
    // We'll use that.

    MOVQ 15*8(RSP), RSI   // vector
    CALL ·handleInterrupt(SB)

    // Restore registers
    POPQ R15
    POPQ R14
    POPQ R13
    POPQ R12
    POPQ R11
    POPQ R10
    POPQ R9
    POPQ R8
    POPQ RBP
    POPQ RDI
    POPQ RSI
    POPQ RDX
    POPQ RCX
    POPQ RBX
    POPQ RAX

    // Remove vector and error from stack
    ADDQ $16, RSP

    IRETQ

// Now generate stubs for vectors 0-255.
// We'll use a simple approach: define each via macro.
// We'll define a macro that expands to the function.
#define GEN_STUB(vector) \
TEXT ·isr_##vector(SB), NOSPLIT, $0; \
    PUSHQ $0; \
    PUSHQ $vector; \
    JMP common_isr_handler;

// For vectors with error codes: 8, 10-14, 17, 30
#define GEN_STUB_ERR(vector) \
TEXT ·isr_##vector(SB), NOSPLIT, $0; \
    PUSHQ $vector; \
    JMP common_isr_handler;

// Generate stubs for 0-255
// We'll generate a few manually, and the rest can be generated by a script.
// For now, we'll define 0-31.

GEN_STUB(0)
GEN_STUB(1)
GEN_STUB(2)
GEN_STUB(3)
GEN_STUB(4)
GEN_STUB(5)
GEN_STUB(6)
GEN_STUB(7)
GEN_STUB_ERR(8)
GEN_STUB(9)
GEN_STUB_ERR(10)
GEN_STUB_ERR(11)
GEN_STUB_ERR(12)
GEN_STUB_ERR(13)
GEN_STUB_ERR(14)
GEN_STUB(15)
GEN_STUB(16)
GEN_STUB(17)
GEN_STUB(18)
GEN_STUB(19)
GEN_STUB(20)
GEN_STUB(21)
GEN_STUB(22)
GEN_STUB(23)
GEN_STUB(24)
GEN_STUB(25)
GEN_STUB(26)
GEN_STUB(27)
GEN_STUB(28)
GEN_STUB(29)
GEN_STUB_ERR(30)
GEN_STUB(31)

// For IRQ 0-15, we'll map to vectors 32-47.
GEN_STUB(32)
GEN_STUB(33)
GEN_STUB(34)
GEN_STUB(35)
GEN_STUB(36)
GEN_STUB(37)
GEN_STUB(38)
GEN_STUB(39)
GEN_STUB(40)
GEN_STUB(41)
GEN_STUB(42)
GEN_STUB(43)
GEN_STUB(44)
GEN_STUB(45)
GEN_STUB(46)
GEN_STUB(47)

// For the rest, we'll generate a generic stub that calls a default handler.
// We'll use a macro that generates a stub that pushes the vector and calls common.
// But we can just generate them via a script in the build system. For now, we'll rely on the fact that we will use a per-vector function pointer table.
// We'll just define a generic stub for all other vectors: push vector, jmp common.
// But we need a distinct function for each vector because we need to push the correct vector number.
// We'll use a trick: we'll define a single function that reads the vector from the frame? Not possible.
// So we'll generate them by a script in the build process. For this code, we'll include a placeholder that will be generated.

// For demonstration, we'll provide a function that sets up all entries to use a generic stub that reads a global variable? Not possible.
// We'll assume the build script generates the stubs.

// In practice, we can create a small program to generate isr_vectors.asm and include it.
// For now, we'll manually define a few and note that the rest will be generated.

// We'll also define a default stub that loads a vector from a global? Not feasible.
// So we'll go with the approach of generating all stubs.
// To keep the code small, we'll generate using a script in the build process.
