package interrupts

import (
	"rtos/lib"
	"unsafe"
)

// handleInterrupt is called from the ISR stubs (generated by gen_isr.py)
func handleInterrupt(context *unsafe.Pointer, vector uint8) {
	if vector == 32 {
		TimerHandler()
		return
	}
	// ... handle other interrupts here
	lib.PrintString("Interrupt: ")
	lib.PrintUint64(uint64(vector))
	lib.PrintString("\n")
}
